/* tslint:disable */
require("./styles.module.css");
const styles = {
  ride: 'ride_dcd20dec',
  rideContent: 'rideContent_dcd20dec',
  rideHead: 'rideHead_dcd20dec',
  top: 'top_dcd20dec',
  rideFormBar: 'rideFormBar_dcd20dec',
  rideFormcontent: 'rideFormcontent_dcd20dec',
  from: 'from_dcd20dec',
  to: 'to_dcd20dec',
  rideForm: 'rideForm_dcd20dec',
  'submit-button': 'submit-button_dcd20dec',
  next: 'next_dcd20dec',
  stops: 'stops_dcd20dec',
  viapoints: 'viapoints_dcd20dec',
  rideFormContinue: 'rideFormContinue_dcd20dec',
  plus: 'plus_dcd20dec',
  seats: 'seats_dcd20dec',
  sectionB: 'sectionB_dcd20dec',
  offerPrice: 'offerPrice_dcd20dec',
  'upload-button': 'upload-button_dcd20dec',
  minus: 'minus_dcd20dec',
  section1: 'section1_dcd20dec',
  msg: 'msg_dcd20dec',
  edit: 'edit_dcd20dec',
  delete: 'delete_dcd20dec',
  decrease: 'decrease_dcd20dec',
  allmatches: 'allmatches_dcd20dec',
  formWidthLess: 'formWidthLess_dcd20dec',
  formWidthMore: 'formWidthMore_dcd20dec',
  suggestionResult: 'suggestionResult_dcd20dec',
  positionRelative: 'positionRelative_dcd20dec',
  dateTime: 'dateTime_dcd20dec',
  VehicleInfo: 'VehicleInfo_dcd20dec',
  discount: 'discount_dcd20dec',
  vehicleType: 'vehicleType_dcd20dec',
  timePicker: 'timePicker_dcd20dec',
  timeContainer: 'timeContainer_dcd20dec',
  timeHolder: 'timeHolder_dcd20dec',
  seatContainer: 'seatContainer_dcd20dec',
  seatHolder: 'seatHolder_dcd20dec',
  main_error_msg: 'main_error_msg_dcd20dec',
  blinkingText: 'blinkingText_dcd20dec'
};

export default styles;
/* tslint:enable */