/* tslint:disable */
require("./styles.module.css");
const styles = {
  ride: 'ride_bdf74a0d',
  rideContent: 'rideContent_bdf74a0d',
  rideHead: 'rideHead_bdf74a0d',
  top: 'top_bdf74a0d',
  rideFormBar: 'rideFormBar_bdf74a0d',
  rideFormcontent: 'rideFormcontent_bdf74a0d',
  from: 'from_bdf74a0d',
  to: 'to_bdf74a0d',
  rideForm: 'rideForm_bdf74a0d',
  'submit-button': 'submit-button_bdf74a0d',
  next: 'next_bdf74a0d',
  stops: 'stops_bdf74a0d',
  viapoints: 'viapoints_bdf74a0d',
  rideFormContinue: 'rideFormContinue_bdf74a0d',
  plus: 'plus_bdf74a0d',
  seats: 'seats_bdf74a0d',
  sectionB: 'sectionB_bdf74a0d',
  offerPrice: 'offerPrice_bdf74a0d',
  'upload-button': 'upload-button_bdf74a0d',
  minus: 'minus_bdf74a0d',
  section1: 'section1_bdf74a0d',
  msg: 'msg_bdf74a0d',
  edit: 'edit_bdf74a0d',
  delete: 'delete_bdf74a0d',
  decrease: 'decrease_bdf74a0d',
  allmatches: 'allmatches_bdf74a0d',
  formWidthLess: 'formWidthLess_bdf74a0d',
  formWidthMore: 'formWidthMore_bdf74a0d',
  suggestionResult: 'suggestionResult_bdf74a0d',
  positionRelative: 'positionRelative_bdf74a0d',
  dateTime: 'dateTime_bdf74a0d',
  VehicleInfo: 'VehicleInfo_bdf74a0d',
  discount: 'discount_bdf74a0d',
  vehicleType: 'vehicleType_bdf74a0d',
  timePicker: 'timePicker_bdf74a0d',
  timeContainer: 'timeContainer_bdf74a0d',
  timeHolder: 'timeHolder_bdf74a0d',
  seatContainer: 'seatContainer_bdf74a0d',
  seatHolder: 'seatHolder_bdf74a0d',
  main_error_msg: 'main_error_msg_bdf74a0d',
  blinkingText: 'blinkingText_bdf74a0d'
};

export default styles;
/* tslint:enable */